spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/forum_db
    username: lulu
    password: 123456
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true